### ISSUE TITLE
Implementation of Singly and Doubly Linked List

### ISSUE THREAD

**Issue by RAGHAVS1304** [Eshaabhasin/Hacktoberfest2023repo#11]
Implementation of Singly and Doubly Linked List separately with all their basic functions created using OOPS.

**Comment by RAGHAVS1304** [comment]
Greetings Mam,
Please assign this issue to me, i will be providing my codes for these Topics.
Thanks.

**Comment by Eshaabhasin** [comment]
Sure !

**Comment by RAGHAVS1304** [comment]
Mam i have raised the PR, please review it.
