### ISSUE TITLE
Fundamentals of Stack Data Structure

### ISSUE THREAD

**Issue by RAGHAVS1304** [Eshaabhasin/Hacktoberfest2023repo#13]
- Implementation using array
- Implementation using linked list
- infix to postfix
- infix to prefix
- postfix evaluation
- prefix evaluation
- language used: C++

**Comment by RAGHAVS1304** [comment]
Mam please assign this to me

**Comment by RAGHAVS1304** [comment]
Mam I have raised the PR please review it.
Thanks.

**Comment by Eshaabhasin** [comment]
Awesome!
